# Generated by Django 4.2.23 on 2025-07-31 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_alter_rating_r_date'),
    ]

    operations = [
    ]
