# Generated by Django 4.2.23 on 2025-08-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_alter_bill_phone_alter_order_phone_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='pic',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_name',
            field=models.CharField(default='default.webp', max_length=50),
        ),
    ]
